MAPS_DICT = {
                "blizzard world": "./Images/blizzardworld_plain.webp",
                "dorado": "./Images/dorado_plain.webp",
                "eichenwalde": "./Images/eichenwalde_plain.webp",
                "hanamura": "./Images/hanamura_plain.webp",
                "hollywood": "./Images/hollywood_plain.webp",
                "horizon": "./Images/horizonlunarcolony_plain_updated.webp",
                "ilios": "./Images/ilios_plain.webp",
                "junkertown": "./Images/junkertown_plain.webp",
                "king's row": "./Images/kingsrow_plain.webp",
                "lijiang tower": "./Images/lijiangtower_plain.webp",
                "nepal": "./Images/nepal_plain.webp",
                "numbani": "./Images/numbani_plain.webp",
                "oasis": "./Images/oasis_plain.webp",
                "rialto": "./Images/rialto_plain.webp",
                "route 66": "./Images/route66_plain.webp",
                "temple of anubis": "./Images/templeofanubis_plain.webp",
                "volskaya": "./Images/volskayaindustries_plain.webp",
                "watchpoint: gibraltar": "./Images/watchpointgibraltar_plain.webp",
            }